### ISSUE TITLE
dev-4.0: Port away from boost::thread

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/gr-digitizers#110]
Check all usage of boost thread and replace with std::jthread etc. (some code is using boost::thread features not present in C++11 std::thread). Also replace boost mutex and locks with their STL equivalents.

One of them:

        Could be replaced with `std::jthread`, likely even without the pointer indirection.

_Originally posted by @ivan-cukic in https://github.com/fair-acc/gr-digitizers/pull/108#discussion_r1035685113_

**Comment by RalphSteinhagen** [comment]
graph-prototype deploys a new thread pool scheme which we should use and obsolete this particular issue.
