### ISSUE TITLE
dev-4.0: Port away from boost::bind

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/gr-digitizers#111]
Replace boost::bind usage with modern C++ equivalents.

E.g.

        Could be replaced with std::bind_front or a lambda - bind is slow

_Originally posted by @ivan-cukic in https://github.com/fair-acc/gr-digitizers/pull/108#discussion_r1035686471_

**Comment by RalphSteinhagen** [comment]
obsoleted in graph-prototype/GR 4.0 - closing this in favour of moving to the new framework.
