### ISSUE TITLE
[1pt] graph-prototype: Review TODO(PORT) comments and PORT_DISABLED macros

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/gr-digitizers#114]
The code contains quite a few TODO(PORT) comments and disabled code using `#ifdef PORT_DISABLED`.
They can stem from me not being sure on GR's behavior, limitations in GR, etc.

Clarify them, find solutions where possible, report feature requests to GR proper where it would make sense, etc.

**Comment by RalphSteinhagen** [comment]
review if these TODO's are still applicable in graph-prototype/the new GR 4.0

**Comment by RalphSteinhagen** [comment]
linked to #113

**Comment by RalphSteinhagen** [comment]
I think this can be closed since I found only one remaining `PORT_DISABLED` reference regarding a logging of a warning message. This should/will be addressed by: https://github.com/fair-acc/gr-digitizers/issues/113

**Comment by frankosterfeld** [comment]
This was referring to the old dev-4.0 branch and is of course only relevant if we decide to port any of the blocks in there.
