### ISSUE TITLE
dev-4.0: Make our blocks usable in GRC and port examples

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/gr-digitizers#115]
As there is no functional QT GUI sink equivalent in GR 4.0 yet, I relied on the unit tests and didn't spend time with the examples/ folder or used the blocks in GRC.
Review what of the examples/ folder from before the port is worth keeping, either as GRC example or converted to a unit test.

**Comment by RalphSteinhagen** [comment]
This is superseded by the opendigitizer-UI: https://fair-acc.github.io/opendigitizer/
