### ISSUE TITLE
Bug when running ps3000 scope with < 500mV Range in Rapid Block mode

### ISSUE THREAD

**Issue by alexxcons** [fair-acc/gr-digitizers#79]
Seens on dal005 (schottky system) 

Triggering is done, samples are passed to the sink/client, but all samples are 0, the CPU load goes up and event-matching fails (only ~30 matched events)

500mV Range seems to work fine.

Reproducer: 

- 1.2M Post Trigger samples, no pre-trigger samples
- Only a Time Sink on the port0 (first digital Port)
- Samp Rate: 62.5MS/s
- No downsampling

Edit: Attached reproducer. Possible the concrete type of the ps3000 scope matters

According to scope manual, `± 100 mV to ± 20 V in 8 ranges` should work.
(For 3224 and 3424 : `± 20 mV to ± 20 V in 10 ranges`) <-- What exact scope do we use ? Does the software consider the difference ? Possibly that diference matters !

Very confusing is, that the Digital Port is influenced by the Range-Value picked for the analog ports.

[dal005.grc.zip](https://github.com/fair-acc/gr-digitizers/files/7292656/dal005.grc.zip)

**Comment by alexxcons** [comment]
Possibly related to https://github.com/fair-acc/gr-digitizers/pull/98

**Comment by RalphSteinhagen** [comment]
> [..] no pre-trigger samples [..]

You need a few samples before, otherwise you won't be able to see the rising trigger edge which technically lies on sample number '0' (or '-1').

**Comment by alexxcons** [comment]
> > [..] no pre-trigger samples [..]
> 
> You need a few samples before, otherwise you won't be able to see the rising trigger edge which technically lies on sample number '0' (or '-1').

Haha, that looks like it was a "problem sitting in front of screen"  usecase :P  I will re-test when I have time !

**Comment by alexxcons** [comment]
> Haha, that looks like it was a "problem sitting in front of screen" usecase :P I will re-test when I have time !

Cannot reproduce this issue any more. The above reproducer .grc runs/triggers fine now on dal004 and dal005 (both 3403DMSO scopes). The use-case 'no pre trigger samples' not even seems to be a problem.

I went down to just having a single trigger-sample .. still works fine.

No idea what I tested before --> closing the issue.
